version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: auction-rabbitmq
    ports:
      - "5672:5672"    # AMQP port (for your Go app to connect)
      - "15672:15672"  # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - auction-network

volumes:
  rabbitmq_data:

networks:
  auction-network:
    driver: bridge