# application.yml (SAME for Auth, Item, Auction services)
spring:
  cloud:
    stream:
      bindings:
        eventChannel-out-0:
          destination: resource-events-exchange
      rabbit:
        bindings:
          eventChannel-out-0:
            producer:
              exchangeType: topic
              routing-key-expression: headers['routingKey']